print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")
print("5.Factorial")
print("6.Square Root")
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))